---
- hosts: server
  gather_facts: no
  become: yes
  tasks:
  - name: Create xsn user
    user:
      name: xsn-user
      state: present

  - name: Verify if xsn-core exists
    stat:
      path: /home/xsn-user/xsn-1.0.21-x86_64-linux-gnu.tar.gz
    register: stat_result

  - name: Download the application
    get_url:
      url: https://github.com/X9Developers/XSN/releases/download/v1.0.21/xsn-1.0.21-x86_64-linux-gnu.tar.gz
      dest: /home/xsn-user
      mode: '0440'
    when: stat_result.stat.exists == False

  - name: Unpack the application
    unarchive:
      remote_src: yes
      src: /home/xsn-user/xsn-1.0.21-x86_64-linux-gnu.tar.gz
      dest: /home/xsn-user
      owner: xsn-user
      group: xsn-user

  - name: Create xsncore directory
    file:
      path: /home/xsn-user/.xsncore
      state: directory
      owner: xsn-user
      group: xsn-user

  - name: Add conf file
    copy:
      src: xsn.conf
      dest: /home/xsn-user/.xsncore/xsn.conf
      owner: xsn-user
      group: xsn-user

  - name: Add the application service
    copy:
      src: xsnd.service
      dest: /etc/systemd/system
    notify:
    - Pick up systemd changes
    - Restart the application
    - Enable the application to run on system startup

  handlers:
  - name: Pick up systemd changes
    systemd:
      daemon_reload: yes

  - name: Restart the application
    systemd:
      name: xsnd
      state: restarted

  - name: Enable the application to run on system startup
    systemd:
      name: xsnd
      enabled: yes
